include(ExternalProject)

externalproject_add(g2o
    PREFIX "external/g2o"
    GIT_REPOSITORY "https://github.com/RainerKuemmerle/g2o.git"
    GIT_TAG "17fce87df9d5b2aa7b4239be1fbac9d40c95d72f"
    CMAKE_ARGS "-DCMAKE_BUILD_TYPE=Release -DG2O_BUILD_EXAMPLES=OFF -DG2O_BUILD_APPS=OFF"
    INSTALL_COMMAND ""
)

externalproject_get_property(g2o SOURCE_DIR BINARY_DIR)

externalproject_add_step(g2o copy_config
    COMMAND ${CMAKE_COMMAND} -E copy "${BINARY_DIR}/g2o/config.h" "${SOURCE_DIR}/g2o"
    DEPENDEES build
)

set(G2O_INCLUDE_DIRS
    "${SOURCE_DIR}"
    "${SOURCE_DIR}/EXTERNAL/ceres"
    "${SOURCE_DIR}/EXTERNAL/csparse"
    "${SOURCE_DIR}/EXTERNAL/freeglut"
)

set(G2O_LIBRARIES
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_calibration_odom_laser${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_cli${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_core${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_csparse_extension${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_ext_freeglut_minimal${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_hierarchical${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_incremental${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_interactive${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_interface${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_opengl_helper${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_parser${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_simulator${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_solver_cholmod${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_solver_csparse${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_solver_dense${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_solver_eigen${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_solver_pcg${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_solver_slam2d_linear${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_solver_structure_only${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_stuff${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_tutorial_slam2d${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_types_data${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_types_icp${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_types_sba${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_types_sclam2d${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_types_sim3${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_types_slam2d_addons${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_types_slam2d${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_types_slam3d_addons${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_types_slam3d${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "${SOURCE_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}g2o_viewer${CMAKE_SHARED_LIBRARY_SUFFIX}"
)
